name: Build

on:
  push:
    branches: [ master, feature/** ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, android, ios, darwin]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Install fine-cross compiler
        run: go install github.com/fyne-io/fyne-cross@v1.2.1
      - name: Install fyne
        run: go install fyne.io/fyne/v2/cmd/fyne@latest
      - name: Build
        run: fyne-cross ${{ matrix.os }} -app-id com.plur.beemobile -icon Icon.png